include!("lib_tests/endpoints.rs");
include!("lib_tests/map.rs");
include!("lib_tests/scene.rs");
include!("lib_tests/cognition.rs");
include!("lib_tests/observatory.rs");
include!("lib_tests/observatory_source.rs");
include!("lib_tests/observatory_ui.rs");
include!("lib_tests/observatory_graph.rs");
include!("lib_tests/observatory_authority.rs");
