#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
pub enum CockpitEventKind {
    Boot,
    CommandAccepted,
    CommandRejected,
    CommandStarted,
    CommandCompleted,
    CommandInterrupted,
    CommandTimedOut,
    CommandRenewed,
    BodyPowerRequested,
    BodyPowerChanged,
    BodyModeRequested,
    BodyModeChanged,
    TelemetryReceived,
    SensorFrameDecoded,
    MotionRequested,
    MotionStopped,
    SafetyTripped,
    SafetyCleared,
    BumpChanged,
    CliffChanged,
    WheelDropLatched,
    WheelDropCleared,
    WallChanged,
    VirtualWallChanged,
    BatteryLow,
    ChargingStateChanged,
    ButtonsChanged,
    IrChanged,
    HeartbeatExpired,
    EStopLatched,
    EStopCleared,
    ImuFrameReceived,
    ImuFault,
    TiltChanged,
    ImuCalibrationChanged,
    MotionInconsistencyDetected,
    ImpactDetected,
    SessionOpened,
    SessionReplaced,
    SessionClosed,
    SessionRejected,
    PeerRebootDetected,
    TransportChanged,
    DhcpLeaseChanged,
    DnsRegistrationChanged,
    AuthorityChanged,
    MotherbrainResetRequested,
    MotherbrainResetAsserted,
    MotherbrainResetCompleted,
    MotherbrainResetRefused,
    ContactWithdrawalStarted,
    ContactWithdrawalCompleted,
    AudioStateChanged,
    Error,
    Unknown(String),
}

impl From<&str> for CockpitEventKind {
    fn from(kind: &str) -> Self {
        match kind {
            "boot" => Self::Boot,
            "command_accepted" => Self::CommandAccepted,
            "command_rejected" => Self::CommandRejected,
            "command_started" => Self::CommandStarted,
            "command_completed" => Self::CommandCompleted,
            "command_interrupted" => Self::CommandInterrupted,
            "command_timed_out" => Self::CommandTimedOut,
            "command_renewed" => Self::CommandRenewed,
            "body_power_requested" => Self::BodyPowerRequested,
            "body_power_changed" => Self::BodyPowerChanged,
            "body_mode_requested" => Self::BodyModeRequested,
            "body_mode_changed" => Self::BodyModeChanged,
            "telemetry_received" => Self::TelemetryReceived,
            "sensor_frame_decoded" => Self::SensorFrameDecoded,
            "motion_requested" => Self::MotionRequested,
            "motion_stopped" => Self::MotionStopped,
            "safety_tripped" => Self::SafetyTripped,
            "safety_cleared" => Self::SafetyCleared,
            "bump_changed" => Self::BumpChanged,
            "cliff_changed" => Self::CliffChanged,
            "wheel_drop_latched" => Self::WheelDropLatched,
            "wheel_drop_cleared" => Self::WheelDropCleared,
            "wall_changed" => Self::WallChanged,
            "virtual_wall_changed" => Self::VirtualWallChanged,
            "battery_low" => Self::BatteryLow,
            "charging_state_changed" => Self::ChargingStateChanged,
            "buttons_changed" => Self::ButtonsChanged,
            "ir_changed" => Self::IrChanged,
            "heartbeat_expired" => Self::HeartbeatExpired,
            "estop_latched" => Self::EStopLatched,
            "estop_cleared" => Self::EStopCleared,
            "imu_frame_received" => Self::ImuFrameReceived,
            "imu_fault" => Self::ImuFault,
            "tilt_changed" => Self::TiltChanged,
            "imu_calibration_changed" => Self::ImuCalibrationChanged,
            "motion_inconsistency_detected" => Self::MotionInconsistencyDetected,
            "impact_detected" => Self::ImpactDetected,
            "session_opened" => Self::SessionOpened,
            "session_replaced" => Self::SessionReplaced,
            "session_closed" => Self::SessionClosed,
            "session_rejected" => Self::SessionRejected,
            "peer_reboot_detected" => Self::PeerRebootDetected,
            "transport_changed" => Self::TransportChanged,
            "dhcp_lease_changed" => Self::DhcpLeaseChanged,
            "dns_registration_changed" => Self::DnsRegistrationChanged,
            "authority_changed" => Self::AuthorityChanged,
            "motherbrain_reset_requested" => Self::MotherbrainResetRequested,
            "motherbrain_reset_asserted" => Self::MotherbrainResetAsserted,
            "motherbrain_reset_completed" => Self::MotherbrainResetCompleted,
            "motherbrain_reset_refused" => Self::MotherbrainResetRefused,
            "contact_withdrawal_started" => Self::ContactWithdrawalStarted,
            "contact_withdrawal_completed" => Self::ContactWithdrawalCompleted,
            "audio_state_changed" => Self::AudioStateChanged,
            "error" => Self::Error,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

impl CockpitEventKind {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Boot => "boot",
            Self::CommandAccepted => "command_accepted",
            Self::CommandRejected => "command_rejected",
            Self::CommandStarted => "command_started",
            Self::CommandCompleted => "command_completed",
            Self::CommandInterrupted => "command_interrupted",
            Self::CommandTimedOut => "command_timed_out",
            Self::CommandRenewed => "command_renewed",
            Self::BodyPowerRequested => "body_power_requested",
            Self::BodyPowerChanged => "body_power_changed",
            Self::BodyModeRequested => "body_mode_requested",
            Self::BodyModeChanged => "body_mode_changed",
            Self::TelemetryReceived => "telemetry_received",
            Self::SensorFrameDecoded => "sensor_frame_decoded",
            Self::MotionRequested => "motion_requested",
            Self::MotionStopped => "motion_stopped",
            Self::SafetyTripped => "safety_tripped",
            Self::SafetyCleared => "safety_cleared",
            Self::BumpChanged => "bump_changed",
            Self::CliffChanged => "cliff_changed",
            Self::WheelDropLatched => "wheel_drop_latched",
            Self::WheelDropCleared => "wheel_drop_cleared",
            Self::WallChanged => "wall_changed",
            Self::VirtualWallChanged => "virtual_wall_changed",
            Self::BatteryLow => "battery_low",
            Self::ChargingStateChanged => "charging_state_changed",
            Self::ButtonsChanged => "buttons_changed",
            Self::IrChanged => "ir_changed",
            Self::HeartbeatExpired => "heartbeat_expired",
            Self::EStopLatched => "estop_latched",
            Self::EStopCleared => "estop_cleared",
            Self::ImuFrameReceived => "imu_frame_received",
            Self::ImuFault => "imu_fault",
            Self::TiltChanged => "tilt_changed",
            Self::ImuCalibrationChanged => "imu_calibration_changed",
            Self::MotionInconsistencyDetected => "motion_inconsistency_detected",
            Self::ImpactDetected => "impact_detected",
            Self::SessionOpened => "session_opened",
            Self::SessionReplaced => "session_replaced",
            Self::SessionClosed => "session_closed",
            Self::SessionRejected => "session_rejected",
            Self::PeerRebootDetected => "peer_reboot_detected",
            Self::TransportChanged => "transport_changed",
            Self::DhcpLeaseChanged => "dhcp_lease_changed",
            Self::DnsRegistrationChanged => "dns_registration_changed",
            Self::AuthorityChanged => "authority_changed",
            Self::MotherbrainResetRequested => "motherbrain_reset_requested",
            Self::MotherbrainResetAsserted => "motherbrain_reset_asserted",
            Self::MotherbrainResetCompleted => "motherbrain_reset_completed",
            Self::MotherbrainResetRefused => "motherbrain_reset_refused",
            Self::ContactWithdrawalStarted => "contact_withdrawal_started",
            Self::ContactWithdrawalCompleted => "contact_withdrawal_completed",
            Self::AudioStateChanged => "audio_state_changed",
            Self::Error => "error",
            Self::Unknown(kind) => kind.as_str(),
        }
    }
}

